version: '3.8'
services:
  httpd:
    image: httpd:2.4.57
    container_name: httpd
    ports:
      - 80:80
    links:
      - fluentd
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: httpd.access

  fluentd:
    image: fluentd:v1.16-debian-1
    container_name: fluentd
    volumes:
      - ./config:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - 24224:24224

  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    volumes:
      - ./kibana:/usr/share/kibana
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.8.1
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
