version: '3.8'

services:
  cdn:
    container_name: cdn
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - 0.0.0.0:4400:80
      - 0.0.0.0:4401:81
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./assets:/assets
      - ./games:/games
