version: '3.8'

services:
  cdn:
    container_name: cdn
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./assets:/assets
