version: '3.8'

services:
  keepalived:
    image: keepalived:2.2.8
    container_name: keepalived
    restart: unless-stopped
    volumes:
      - ./keepalived1.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:80
