version: '3.8'

services:
  haproxy:
    image: haproxy:2.7-alpine3.17
    container_name: haproxy
    restart: unless-stopped

  postgres:
    image: 2.7-alpine3.17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U kong -d kong'" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kong-migration:
    image: kong:3.3.0
    container_name: kong-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap

  kong:
    image: kong:3.3.0
    container_name: kong
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - postgres:postgres
    ports:
      - 0.0.0.0:80:8000
      - 0.0.0.0:443:8443
      - 0.0.0.0:8001:8001
      - 0.0.0.0:8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl

  kong-admin-ui:
    image: pocketdigi/kong-admin-ui:0.5.3
    container_name: kong-admin-ui
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:80
