version: '3.8'

services:
  haproxy:
    image: haproxy:2.7.8-alpine3.17
    container_name: haproxy
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 0.0.0.0:80:80

  apache1:
    image: ubuntu/apache2:latest
    container_name: apache1
    restart: unless-stopped
    ports:
      - 0.0.0.0:81:80

  apache2:
    image: ubuntu/apache2:latest
    container_name: apache2
    restart: unless-stopped
    ports:
      - 0.0.0.0:82:80
