version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine3.17
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - kong1
      - kong2
    ports:
      - 0.0.0.0:80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/var/log/nginx:/var/log/nginx
    command: /bin/sh -c "nginx -g 'daemon off;'"

  postgres:
    image: postgres:15.3-alpine3.17
    container_name: postgres
    restart: unless-stopped
    # ports:
    #   - 0.0.0.0:5432:5432
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U kong -d kong'" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kong-migration:
    image: kong:3.3.0
    container_name: kong-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap

  kong1:
    image: kong:3.3.0
    container_name: kong1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - postgres:postgres
    ports:
      - 0.0.0.0:8000:8000
      - 0.0.0.0:8080:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl

  kong2:
    image: kong:3.3.0
    container_name: kong2
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - postgres:postgres
    ports:
      - 0.0.0.0:8001:8000
      - 0.0.0.0:8081:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
