version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25-alpine3.17
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /etc/letsencrypt/live/gamecms.metaserv.vn/fullchain.pem:/etc/nginx/ssl/live/gamecms.metaserv.vn/fullchain.pem
      - /etc/letsencrypt/live/gamecms.metaserv.vn/privkey.pem:/etc/nginx/ssl/live/gamecms.metaserv.vn/privkey.pem
      - /etc/letsencrypt/live/gamecp.metaserv.vn/fullchain.pem:/etc/nginx/ssl/live/gamecp.metaserv.vn/fullchain.pem
      - /etc/letsencrypt/live/gamecp.metaserv.vn/privkey.pem:/etc/nginx/ssl/live/gamecp.metaserv.vn/privkey.pem
      - /etc/letsencrypt/live/gameportal.metaserv.vn/fullchain.pem:/etc/nginx/ssl/live/gameportal.metaserv.vn/fullchain.pem
      - /etc/letsencrypt/live/gameportal.metaserv.vn/privkey.pem:/etc/nginx/ssl/live/gameportal.metaserv.vn/privkey.pem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
