version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25-alpine3.17
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 103.20.144.134:80:80
      - 103.20.144.134:443:443
    volumes:
      - /etc/letsencrypt/live/image.metaserv.vn/fullchain.pem:/etc/nginx/ssl/live/image.metaserv.vn/fullchain.pem
      - /etc/letsencrypt/live/image.metaserv.vn/privkey.pem:/etc/nginx/ssl/live/image.metaserv.vn/privkey.pem
      - /etc/letsencrypt/live/video.metaserv.vn/fullchain.pem:/etc/nginx/ssl/live/video.metaserv.vn/fullchain.pem
      - /etc/letsencrypt/live/video.metaserv.vn/privkey.pem:/etc/nginx/ssl/live/video.metaserv.vn/privkey.pem
      - ./nginx.134.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
