version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine3.17
    container_name: nginx
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt/live:/etc/nginx/ssl/live
