version: '3.8'

services:
  keepalived1:
    image: keepalived:2.2.8
    container_name: keepalived1
    restart: unless-stopped
    volumes:
      - ./keepalived1.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      - KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.0.21', '192.168.0.22']"
      - KEEPALIVED_VIRTUAL_IPS=192.168.0.20
      - KEEPALIVED_PRIORITY=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      nginx-network:
        ipv4_address: 192.168.0.21

  keepalived2:
    image: keepalived:2.2.8
    container_name: keepalived2
    restart: unless-stopped
    volumes:
      - ./keepalived2.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      - KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.0.21', '192.168.0.22']"
      - KEEPALIVED_VIRTUAL_IPS=192.168.0.20
      - KEEPALIVED_PRIORITY=2
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      nginx-network:
        ipv4_address: 192.168.0.22

  haproxy1:
    image: haproxy:2.7.8-alpine3.17
    container_name: haproxy1
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      nginx-network:
        ipv4_address: 192.168.0.31

  haproxy2:
    image: haproxy:2.7.8-alpine3.17
    container_name: haproxy2
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      nginx-network:
        ipv4_address: 192.168.0.32

networks:
  nginx-network:
    name: nginx-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
