version: '3.8'

services:
  keepalived1:
    image: keepalived:2.2.8
    container_name: keepalived1
    restart: unless-stopped
    volumes:
      - ./keepalived1.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    depends_on:
      - kong1
      - kong2

  keepalived2:
    image: keepalived:2.2.8
    container_name: keepalived2
    restart: unless-stopped
    volumes:
      - ./keepalived2.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    depends_on:
      - kong1
      - kong2

  postgres:
    image: postgres:15.3-alpine3.17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U kong -d kong'" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kong-migration:
    image: kong:3.3.0-alpine
    container_name: kong-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap

  kong1:
    image: kong:3.3.0-alpine
    container_name: kong1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - postgres:postgres
    ports:
      - 127.0.0.1:8081:8000
      - 0.0.0.0:8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl

  kong2:
    image: kong:3.3.0-alpine
    container_name: kong2
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - postgres:postgres
    ports:
      - 127.0.0.1:8082:8000
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
