version: '3.8'

services:
  keepalived1:
    image: keepalived:2.2.8
    container_name: keepalived1
    restart: unless-stopped
    volumes:
      - ./keepalived1.conf.bridge:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg.bridge:/usr/local/etc/haproxy/haproxy.cfg
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      nginx-network:
        ipv4_address: 192.168.0.21

  keepalived2:
    image: keepalived:2.2.8
    container_name: keepalived2
    restart: unless-stopped
    volumes:
      - ./keepalived2.conf.bridge:/usr/local/etc/keepalived/keepalived.conf
      - ./haproxy.cfg.bridge:/usr/local/etc/haproxy/haproxy.cfg
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      nginx-network:
        ipv4_address: 192.168.0.22

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 0.0.0.0:8081:80

  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    restart: unless-stopped
    ports:
      - 0.0.0.0:8082:8080

networks:
  nginx-network:
    name: nginx-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
