version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - 0.0.0.0:9092:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    name: kafka_data
    driver: local
