version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine3.17
    container_name: postgres
    restart: unless-stopped
    ports:
      - 0.0.0.0:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U postgres -d postgres'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
